#  11 mar 2025 NUMPY Course

In [1]:
import numpy as np

In [3]:
np.__version__

'2.0.0'

In [5]:
import sys
sys.version

'3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]'

# creating arrays

In [8]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [10]:
type(my_list)

list

#  below code we are converting list to array

In [13]:
# !pip install numpy

In [15]:
arr=np.array(my_list)

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
type(arr)

numpy.ndarray

In [21]:
type(my_list)

list

In [23]:
np. # we learn import function

SyntaxError: invalid syntax (231064539.py, line 1)

In [25]:
np.arange(15) # it displays the output from 0 t0 n-1 numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(3.0)

array([0., 1., 2.])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.arange(10,20) # displays the output from 10 to n-1 numbers.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [41]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [43]:
np.arange()

TypeError: arange() requires stop to be specified.

In [45]:
np.arange(10,30,5) # displays the output from 10 to 30 with step value 5.

array([10, 15, 20, 25])

In [47]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [49]:
np.arange(10,30,5,8) # np.arange takes only 3 arguments

TypeError: Cannot interpret '8' as a data type

In [51]:
np.zeros(10) # key word is 'zeros' not 'zero' &  # parameter tuneing

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.zeros(10,dtype=int)  # hyperparametr tuneing

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [57]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
np.zeros((10,20)) # 10 rows and 20 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [61]:
np.ones(1)

array([1.])

In [63]:
np.ones(1,dtype=int) # in built it takes float value to change from float to int we need to use dtype.

array([1])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [69]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [71]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [73]:
np.ones((5,4,),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
np.twos((2,3)) # Because twos function is not there in np (or)  numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [77]:
rand(3,2)

NameError: name 'rand' is not defined

In [79]:
random.rand(3,2)

NameError: name 'random' is not defined

In [81]:
np.random.rand(5) # displays the random values according to the givrn argumnet.

array([0.92515843, 0.96397338, 0.52200177, 0.39874946, 0.52295291])

In [83]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [85]:
np.random.rand(4)

array([0.1732544 , 0.59325415, 0.3276434 , 0.72955265])

In [87]:
np.random.rand(3,5) # it displays 3 row values and 5 column values

array([[0.9530624 , 0.64988869, 0.41598341, 0.23086147, 0.49494856],
       [0.83758432, 0.66940331, 0.46354494, 0.63368755, 0.3729765 ],
       [0.75619951, 0.47873484, 0.9872537 , 0.92331027, 0.30834396]])

In [89]:
np.random.rand(2,4)

array([[0.55393729, 0.97598314, 0.61906247, 0.75282458],
       [0.52387959, 0.70833001, 0.62916802, 0.99258179]])

In [91]:
np.random.randint(3,5)

3

In [93]:
np.random.randint(2,4) # it displays the random values from the given argumnets

3

In [95]:
np.random.randint(2,4)

3

In [97]:
np.random.randint(2,20)

19

In [400]:
np.random.randint(2,20)

7

In [99]:
np.random.randint(10,20,5) # it displayes the values from 10 to 20 with array size 5.

array([12, 18, 15, 17, 15], dtype=int32)

In [101]:
np.random.randint(1,6,4)

array([3, 2, 4, 5], dtype=int32)

In [103]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
np.arange(1,13).reshape(3,4) # displays the values from 1 t0 13 using arange func,with 3 rows and 4 col with reshape function.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [109]:
np.random.randint(10,40,(10,10)) # displays values from 10 to 40 with 10 by 10 matrix

array([[24, 24, 35, 16, 34, 29, 18, 36, 20, 36],
       [14, 15, 26, 39, 11, 33, 29, 18, 31, 27],
       [13, 17, 30, 22, 34, 34, 25, 29, 36, 21],
       [18, 17, 11, 14, 12, 33, 23, 19, 23, 21],
       [28, 31, 21, 37, 38, 16, 30, 30, 21, 30],
       [15, 25, 25, 38, 37, 27, 16, 38, 30, 19],
       [29, 37, 21, 13, 25, 30, 36, 12, 14, 15],
       [36, 17, 39, 37, 10, 23, 37, 32, 21, 15],
       [34, 16, 23, 38, 27, 27, 22, 30, 19, 10],
       [18, 16, 23, 16, 35, 18, 12, 27, 22, 16]], dtype=int32)

In [111]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [117]:
np.random.randint(5,30,(4,5)) 

array([[10,  5, 13, 14, 17],
       [ 8, 28,  8, 12, 17],
       [ 6, 12, 20, 20, 29],
       [ 6, 13, 23, 17,  8]], dtype=int32)

In [119]:
b=np.random.randint(10,20,(5,4))
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [121]:
type(b)

numpy.ndarray

In [123]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [125]:
b[:]

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [127]:
b[1:3] # displays the rows according to given arguments.

array([[12, 16, 12, 11],
       [16, 13, 19, 11]], dtype=int32)

In [129]:
b[1,2] # displays the number according to given arguments that means in 1 st row 2nd col number displayed.

np.int32(12)

In [131]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [133]:
b[1,3]

np.int32(11)

In [139]:
b[1,-1]

np.int32(11)

In [141]:
b[1:4]

array([[12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14]], dtype=int32)

In [143]:
b[0:4]

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14]], dtype=int32)

In [145]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [170]:
b[0:-2]

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11]], dtype=int32)

In [149]:
b[-4:-2]

array([[12, 16, 12, 11],
       [16, 13, 19, 11]], dtype=int32)

In [151]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [153]:
b[-4:2]

array([[12, 16, 12, 11]], dtype=int32)

In [155]:
a=np.random.randint(10,20,10)
a

array([10, 14, 14, 14, 11, 14, 10, 13, 18, 18], dtype=int32)

In [157]:
id(a)

2281967144464

In [159]:
arr

array([0, 1, 2, 3, 4, 5])

In [161]:
np.random.randint(0,90,(10,10))

array([[10, 45, 84, 36, 66, 73, 48, 44, 28, 80],
       [51, 53, 13,  6, 39, 69, 67, 47, 81, 27],
       [23, 52, 10, 74, 41, 46, 63,  5, 14, 49],
       [74, 17, 73, 44, 83, 76, 25, 84, 51, 19],
       [53, 16, 11, 46, 67, 74, 51, 20, 55,  9],
       [36, 64, 31, 83, 18, 46,  3, 85, 32, 67],
       [22, 81, 74,  5, 54, 79, 84, 83,  7, 89],
       [19, 68, 54, 43, 62,  4, 18, 75, 64, 32],
       [51, 10, 37, 35, 79, 53, 89, 10, 11, 37],
       [83,  8, 11,  3, 80, 71,  0, 36, 23, 37]], dtype=int32)

In [172]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [174]:
b[1:]

array([[12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [176]:
b[:-3]

array([[14, 15, 14, 12],
       [12, 16, 12, 11]], dtype=int32)

In [178]:
b[-5:-3]

array([[14, 15, 14, 12],
       [12, 16, 12, 11]], dtype=int32)

In [180]:
b[-4,2]

np.int32(12)

In [182]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [184]:
b[-1,-3]

np.int32(11)

In [188]:
b[-1,-4]

np.int32(13)

In [190]:
b[-4,-2]

np.int32(12)

In [192]:
b

array([[14, 15, 14, 12],
       [12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14],
       [13, 11, 13, 12]], dtype=int32)

In [194]:
b[-4:-1]

array([[12, 16, 12, 11],
       [16, 13, 19, 11],
       [11, 13, 12, 14]], dtype=int32)

In [196]:
b[-4:1]

array([], shape=(0, 4), dtype=int32)

In [200]:
b[-2:3] 

array([], shape=(0, 4), dtype=int32)

# Operations

In [245]:
a=np.random.randint(10,20,10)
a

array([12, 13, 13, 17, 11, 18, 15, 12, 10, 13], dtype=int32)

In [247]:
id(a)

2281984070960

In [249]:
arr

array([0, 1, 2, 3, 4, 5])

In [253]:
arr2=np.random.randint(0,99,(10,10))
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [255]:
len(arr2)

10

In [257]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [259]:
arr2[1:-7]

array([[26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36]], dtype=int32)

In [261]:
arr2[1:9]

array([[26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90]], dtype=int32)

In [263]:
arr

array([0, 1, 2, 3, 4, 5])

In [265]:
arr[:4]

array([0, 1, 2, 3])

In [267]:
arr2[:]

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [269]:
arr2[1:5]

array([[26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83]], dtype=int32)

In [286]:
arr2[0:9]

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90]], dtype=int32)

In [290]:
arr2[-5:]

array([[98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [292]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [294]:
arr2[-5,2]

np.int32(24)

In [302]:
arr2[5:9]

array([[98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90]], dtype=int32)

In [304]:
arr2[-1:-8] # not displays the matrix when we give two negetive numbers in row &col by using (:) symbol.

array([], shape=(0, 10), dtype=int32)

In [306]:
arr2[-1,-2]

np.int32(61)

In [308]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [310]:
arr2[::-1] # displays the matrix in reverse order that means last row becomes first and first row becomes last.

array([[36, 93, 61, 51, 76, 34, 29, 73, 61, 15],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [96, 50, 43,  6, 10, 22, 46, 35, 22, 60]], dtype=int32)

In [312]:
arr2[::-2] # displays the matrix in reverse with step value 2.

array([[36, 93, 61, 51, 76, 34, 29, 73, 61, 15],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14]], dtype=int32)

In [316]:
arr2[::-3] # displays the matrix in reverse with step value 3.

array([[36, 93, 61, 51, 76, 34, 29, 73, 61, 15],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [96, 50, 43,  6, 10, 22, 46, 35, 22, 60]], dtype=int32)

In [318]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [324]:
arr2[:-3] # displays the total rows & col upto -3 that means -4->(-3-1) using n-1 . Prints upto -4.(from downward 4 row)

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57]], dtype=int32)

In [326]:
arr

array([0, 1, 2, 3, 4, 5])

In [328]:
arr.max()

np.int64(5)

In [330]:
arr.min()

np.int64(0)

In [332]:
arr.mean()

np.float64(2.5)

In [334]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [374]:
arr.meadian()

AttributeError: 'numpy.ndarray' object has no attribute 'meadian'

In [336]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [342]:
arr2[2:-3]

array([[21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57]], dtype=int32)

In [350]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [352]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [358]:
arr2[2:5,2:6] # 2:5 ( displays the rows from 2 to 4) 2:6 (displays the columns fron 2 to 5)

array([[62, 31, 36, 34],
       [46, 49, 45,  3],
       [94, 25, 68, 18]], dtype=int32)

In [356]:
arr2[2:5,2:5]

array([[62, 31, 36],
       [46, 49, 45],
       [94, 25, 68]], dtype=int32)

In [419]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [423]:
arr2[7:5,7:5]

array([], shape=(0, 0), dtype=int32)

In [362]:
arr2

array([[96, 50, 43,  6, 10, 22, 46, 35, 22, 60],
       [26, 69, 30, 97,  6, 11, 23, 24, 83, 14],
       [21,  3, 62, 31, 36, 34, 31, 13, 77, 36],
       [65, 62, 46, 49, 45,  3, 59,  2,  5, 11],
       [94, 13, 94, 25, 68, 18, 36,  3, 29, 83],
       [98, 37, 24, 25,  6, 94,  5, 14, 61, 45],
       [83, 49, 51, 93, 86, 70, 73, 10, 57, 57],
       [96, 25, 71, 96, 79, 36, 44,  1, 64, 92],
       [ 6, 15,  7, 52, 95, 27, 84, 34, 37, 90],
       [36, 93, 61, 51, 76, 34, 29, 73, 61, 15]], dtype=int32)

In [370]:
arr2[1:6,1:5]

array([[69, 30, 97,  6],
       [ 3, 62, 31, 36],
       [62, 46, 49, 45],
       [13, 94, 25, 68],
       [37, 24, 25,  6]], dtype=int32)

In [376]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [378]:
arr

array([0, 1, 2, 3, 4, 5])

In [380]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [382]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [384]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [388]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [390]:
arr

array([0, 1, 2, 3, 4, 5])

In [392]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [394]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [398]:
arr.reshape(2,3,order='A') 

array([[0, 1, 2],
       [3, 4, 5]])

In [402]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [404]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [406]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [408]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [410]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [412]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [414]:
arr

array([0, 1, 2, 3, 4, 5])

In [416]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [431]:
mat=np.arange(0,100).reshape(10,10)

In [433]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [435]:
row=4
col=5

In [437]:
row

4

In [439]:
col

5

In [441]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [443]:
mat[row,col] # here row=4,col=5 that means mat[4,5].

np.int64(45)

In [445]:
mat[4,5]

np.int64(45)

In [447]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [516]:
col=6

In [518]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [520]:
mat[6][7] # from 6 row 7 index value (0r) 7th col.

np.int64(67)

In [694]:
mat[6,7] # from 6 row 7 index value (0r) 7th col.

np.int64(67)

In [522]:
mat[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [524]:
mat[4][9]

np.int64(49)

In [557]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [526]:
mat[:,col] # displays the 6 col,because col=6

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [528]:
mat[row,:] # displays the 4 row,because row=4

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [530]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [532]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [534]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [536]:
mat[8,:]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [561]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [544]:
mat[:6] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [546]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [548]:
row

4

In [550]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [559]:
mat[:col] # displays the 6 rows from starting ,because col=6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [565]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [563]:
mat[col:] # displays the rows from 6 

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [567]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [552]:
mat[:row]  # displays the 4 rows from starting ,because row=4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [554]:
mat[row:]  # displays the rows from 4.

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [569]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [571]:
mat[:,-1] # displays the last column.

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [575]:
mat[:,-5] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [577]:
row

4

In [579]:
col

6

In [581]:
mat[1,4]

np.int64(14)

In [583]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [585]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [587]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [589]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [591]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [593]:
mat[6:] # displays the rows & col from 6 index.

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [595]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [597]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [599]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [601]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [603]:
mat[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [605]:
mat[7:]

array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [613]:
mat[:6:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [615]:
mat[:9:3] # displays upto 9 rows & col with step value 3 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [617]:
mat[::-1] # gives output as reverse matrix and 1st row become last and vice versa.

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [619]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [623]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [633]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [635]:
mat[0,1]

np.int64(1)

In [637]:
mat[1,6]

np.int64(16)

In [639]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [641]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [643]:
mat[1:2,2:4]

array([[12, 13]])

In [645]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [653]:
mat[2:3,2:3] 

array([[22]])

In [655]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [657]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [661]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [659]:
mat[2:3,4:5]

array([[24]])

# masking

In [664]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [666]:
id(mat)

2281985993360

In [668]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [670]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [676]:
mat [mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [678]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [680]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [682]:
mat[mat==50] 

array([50])

In [684]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [686]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [688]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [690]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [692]:
a4 = mat[mat==50]
a4

array([50])

# pyth